name: Build and Release

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}

    steps:

      - name: Checkout src
        uses: actions/checkout@v3

      - name: Install dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install -y build-essential
          sudo apt install -y intel-mkl
          sudo apt install -y libboost-dev
          sudo apt install -y libopencv-dev

      - name: Setup MKL environment
        if: matrix.platform == 'ubuntu-latest'
        run: |
          echo "MKLROOT=/opt/intel/mkl" >> $GITHUB_ENV
          export MKLROOT=/opt/intel/mkl

      - name: Build Project
        run: |
          cd examples/gui_example/
          mkdir build && cd build
          cmake ..
          cmake --build .

      - name: Package Binary
        run: |
          cd examples/gui_example/build
          cp conv_lib_gui_example ../conv_lib_gui-${{ matrix.platform }}
          cd ..
          zip myapp-${{ matrix.platform }}.zip myapp-${{ matrix.platform }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: conv_lib_gui-${{matrix.platform}}
          path: dist/FC_neural_networks_library/